---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: NodePort
  ports:     
    - port: 8017
      name: port3
      protocol: TCP
      targetPort: 8017
      nodePort: 8017
  selector: 
    app: demo
---